### ISSUE TITLE
Add seperate permission for '/pl3xmap hide' without player variable

### ISSUE THREAD

**Issue by Til-Weimann** [pl3xgaming/Pl3xMap#73] opened 2021-08-08 21:26 UTC
Hey,
I think it would be really useful to be able to allow players to hide themselves from the map but not others.
Same goes for show, of course.
Thanks!

**Comment by granny** [comment] 2021-08-10 04:23
duplicate of #21

**Closed by granny** 2021-08-10 04:23 UTC
