### ISSUE TITLE
Could not save map for region <region>

### ISSUE THREAD

**Issue by BlueFyreMatt** [pl3xgaming/Pl3xMap#53] opened 2021-06-05 11:19 UTC
My server console is being spammed with the following error every 15 seconds exactly, whats the cause and how can I fix the regions? The regions vary between 4,5 5,5 4,7 5,7 4,6 4,4 in no particular pattern, the map itself is working fine with no issues: https://maps.smpearth.com/towny/ 

[04:07:50 ERROR]: [Pl3xMap] Could not save map for region 4,5
[04:07:50 WARN]: javax.imageio.IIOException: Caught exception during read: 
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1830)
[04:07:50 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
[04:07:50 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
[04:07:50 WARN]:        at net.pl3x.map.plugin.data.Image.save(Image.java:58)
[04:07:50 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[04:07:50 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:07:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[04:07:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[04:07:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[04:07:50 WARN]: Caused by: java.lang.IndexOutOfBoundsException
[04:07:50 WARN]:        at java.base/java.io.RandomAccessFile.readBytes(Native Method)
[04:07:50 WARN]:        at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:408)
[04:07:50 WARN]:        at java.desktop/javax.imageio.stream.FileImageInputStream.read(FileImageInputStream.java:117)
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.common.SubImageInputStream.read(SubImageInputStream.java:61)
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.common.InputStreamAdapter.read(InputStreamAdapter.java:47)
[04:07:50 WARN]:        at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:198)
[04:07:50 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:242)
[04:07:50 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[04:07:50 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[04:07:50 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
[04:07:50 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[04:07:50 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:199)
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1237)
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1373)
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1506)
[04:07:50 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1823)
[04:07:50 WARN]:        ... 8 more

**Comment by granny** [comment] 2021-08-27 23:14
duplicate of #45

**Closed by granny** 2021-08-27 23:14 UTC
